name: Build JAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean package
        
      - name: Archive JAR
        uses: actions/upload-artifact@v1
        with:
          name: lake-loader-jar
          path: target/lake-loader-0.1.jar
