name: Build JAR

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build with Maven
        run: |
          mvn clean package
          mkdir -p ./artifacts
          cp target/lake-loader-0.1.jar ./artifacts/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lake-loader-jar
          path: ./artifacts
